public class NewCapController {
/*public static String apiEndpoint {
        get { return ( getCustomSetting('ApiEndpoint__c')); }
    }
 
    public static String publicKey {
        get { return ( getCustomSetting('PublicKey__c')); }
    }
 
    private static String getCustomSetting(String customSetting) {
        try {
            return ( String.valueof( GoogleRecaptcha__c.getValues('Recaptcha').get(customSetting) ) );
        }
        catch (Exception e) {
            system.debug('[Recaptcha Exception] it seems the Recaptcha Custom Settings are not available:' + e.getMessage());
            return ('NOK');
        }
    }*/
}
//<span id="mce_SELREST_start" style="overflow:hidden;line-height:0;"></span>